{
  "io.authid.core.containers.user.controllers.TestExceptionController.user.not.found" : "User not found with ID: {0}"
}